/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.fcategoria;
import Logica.fmovimiento_caja;
import Logica.fproductos;
import Logica.fusuarios;
import java.sql.Date;
import java.text.DecimalFormat;
import java.time.LocalDate;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge Román
 */
public class FrmVista2 extends javax.swing.JFrame {

    /**
     * Creates new form FrmVista1
     */
    public FrmVista2() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtbuscar = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lbltotalregistros = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new JTable(){    public boolean isCellEditable(int rowIndex, int colIndex){return false;}
        };
        jPanel2 = new javax.swing.JPanel();
        lbltitulovista = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });
        getContentPane().add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 230, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PENDIENTE", "FINALIZADO", "ANULADO" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 110, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BUSCAR");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 30));

        lbltotalregistros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltotalregistros.setForeground(new java.awt.Color(0, 204, 0));
        lbltotalregistros.setText("jLabel2");
        getContentPane().add(lbltotalregistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 190, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 750, 220));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        lbltitulovista.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbltitulovista.setForeground(new java.awt.Color(255, 255, 255));
        lbltitulovista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulovista.setText("jLabel2");
        jPanel2.add(lbltitulovista);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 770, 320));

        jMenu1.setText("ATAJOS");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DOWN, 0));
        jMenuItem1.setText("Ir a Tabla");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        buscador();        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        buscador();     // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jTable1.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.rowAtPoint(evt.getPoint());
        if (evt.getClickCount() == 2) {
            seleccionar_esta_fila(fila);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked
    public static void cambiarcombo() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo.addElement("ACTIVO");
        modelo.addElement("INACTIVO");
        jComboBox1.setModel(modelo);
    }

    public static void cambiarcombo2() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo.addElement("HABILITADO");
        modelo.addElement("INHABILITADO");
        jComboBox1.setModel(modelo);
    }
    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        int key = evt.getKeyCode();
        if (key == 10) {
            int fila = jTable1.getSelectedRow() - 1;
            if (fila > -1) {
                seleccionar_esta_fila(fila);
            }
            if (fila == 1) {
                seleccionar_esta_fila(jTable1.getRowCount() - 1);
            }
        }
        if (key < 37 || key > 40) {
            txtbuscar.requestFocus();
            txtbuscar.selectAll();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyReleased
    public static int dondebuscar = 0;

    public static void buscador() {
        DefaultTableModel modelo = null;

        if (dondebuscar == 1) {
//            registro [0]=rs.getString("codpedido");
//            registro [1]=rs.getString("proveedores_codproveedores");
//            registro [2]=rs.getString("nombre");
//            registro [3]=rs.getString("fecha");
//            registro [4]=rs.getString("cantprod");
//            registro [5]=rs.getString("estado");
            jComboBox1.setVisible(false);
            fusuarios func = new fusuarios();
            modelo = func.mostrar(txtbuscar.getText());
            jTable1.setModel(modelo);
            lbltotalregistros.setText("TOTAL USUARIO " + Integer.toString(func.totalregistros));
        }

        if (dondebuscar == 2) {
            jComboBox1.setVisible(true);
            fmovimiento_caja func = new fmovimiento_caja();
            modelo = func.mostrar(txtbuscar.getText(), jComboBox1.getSelectedItem().toString());
            jTable1.setModel(modelo);
            //lbltotalregistros.setText("TOTAL PEDIDOS" + Integer.toString(func.totalregistros));

        }
         if (dondebuscar == 3) {
            jComboBox1.setVisible(false);
            txtbuscar.setEnabled(false);
             fcategoria func = new fcategoria();
            modelo = func.mostrar(txtbuscar.getText());
            jTable1.setModel(modelo);
            //lbltotalregistros.setText("TOTAL PEDIDOS" + Integer.toString(func.totalregistros));

        }

        if (dondebuscar == 7) {
            jComboBox1.setVisible(false);
            txtbuscar.setEnabled(false);
            fmovimiento_caja func = new fmovimiento_caja();
            modelo = func.mostraractivos();
            jTable1.setModel(modelo);
            //lbltotalregistros.setText("TOTAL PEDIDOS" + Integer.toString(func.totalregistros));

        }
    }
    public static DefaultTableModel modelo = new DefaultTableModel();

    DecimalFormat format = new DecimalFormat("###,###.##");

    void seleccionar_esta_fila(int fila) {

        if (dondebuscar == 1) {
//               registro[0] = rs.getString("idmovimiento");
//                registro[1] = rs.getString("nrocaja");
//                registro[1] = formatear.format(rs.getDouble("monto_apertura"));
//                registro[2] = formatear.format(rs.getDouble("monto_cierre"));
//                registro[3] = rs.getString("fecha_apertura");
//                registro[4] = rs.getString("fecha_cierre");
//                registro[5] = rs.getString("estado");
//                registro[6] = rs.getString("idusuarios");
//                registro[7] = rs.getString("funcionario");
//                registro[8] = rs.getString("numDocumento");
//                modelo.addRow(registro);;
            FrmApertura_Caja.txtID.setText(jTable1.getValueAt(fila, 0).toString());
            FrmApertura_Caja.txtDocumento.setText(jTable1.getValueAt(fila, 1).toString());
            FrmApertura_Caja.txtnombreapellido.setText(jTable1.getValueAt(fila, 2).toString());

            this.dispose();
        }

        if (dondebuscar == 2) {
//                registro[0] = rs.getString("idmovimiento");
//                registro[1] = rs.getString("num_Caja");
//                registro[2] = formatear.format(rs.getDouble("monto_apertura"));
//                registro[3] = formatear.format(rs.getDouble("monto_cierre"));
//                registro[4] = rs.getString("fecha_apertura");
//                registro[5] = rs.getString("fecha_cierre");
//                registro[6] = rs.getString("estado");
//                registro[7] = rs.getString("idusuarios");
//                registro[8] = rs.getString("funcionario");
//                registro[9] = rs.getString("numDocumento");
            FrmCerrarCaja.habilitar(true);
            FrmCerrarCaja.txtID.setText(jTable1.getValueAt(fila, 7).toString());
            FrmCerrarCaja.txtIDCaja.setText(jTable1.getValueAt(fila, 0).toString());
            FrmCerrarCaja.txtNroCaja.setText(jTable1.getValueAt(fila, 1).toString());
            FrmCerrarCaja.txtDocumento.setText(jTable1.getValueAt(fila, 9).toString());
            FrmCerrarCaja.txtnombreapellido.setText(jTable1.getValueAt(fila, 8).toString());
            FrmCerrarCaja.txtMontoApertura.setText(jTable1.getValueAt(fila, 2).toString());
            FrmCerrarCaja.txtmontocierre.setText(jTable1.getValueAt(fila, 3).toString());
            fmovimiento_caja func = new fmovimiento_caja();
            double apertura = Double.parseDouble(jTable1.getValueAt(fila, 2).toString().replace(".", ""));

            double ingreso = func.mostrarTotalAcumuladoPagosVentas(jTable1.getValueAt(fila, 0).toString());
            double egreso = func.mostrarTotalegreso(jTable1.getValueAt(fila, 0).toString());
            double acumulado = ingreso + apertura;
            double caja = ingreso;
            double capital = acumulado - egreso;
//            FrmCerrarCaja.txtmontoacumulado.setText(String.valueOf((format.format((int) acumulado))));
            FrmCerrarCaja.txtmontoacumulado.setText(String.valueOf((format.format((int) caja))));
            FrmCerrarCaja.txtmontoegreso.setText(String.valueOf((format.format((int) egreso))));
            FrmCerrarCaja.txtcapitalcaja.setText(String.valueOf((format.format((int) capital))));
            this.dispose();
        }
      
        if (dondebuscar == 3) {


            frmproducto2.txtidcategoria.setText(jTable1.getValueAt(fila, 0).toString());
            frmproducto2.txtcategoria.setText(jTable1.getValueAt(fila, 1).toString());
           
            this.dispose();
        }
        if (dondebuscar == 7) {

// registro[0] = rs.getString("idmovimiento");
//                registro[1] = rs.getString("num_Caja");
//                registro[2] = formatear.format(rs.getDouble("monto_apertura"));
//                registro[3] = formatear.format(rs.getDouble("monto_cierre"));
//                registro[4] = rs.getString("fecha_apertura");
//                registro[5] = rs.getString("fecha_cierre");
//                registro[6] = rs.getString("estado");
//                registro[7] = rs.getString("idusuarios");
//                registro[8] = rs.getString("funcionario");
//                registro[9] = rs.getString("numDocumento");
            FrmApertura_Caja.habilitar(true);
            FrmApertura_Caja.txtIDCaja.setText(jTable1.getValueAt(fila, 0).toString());
            FrmApertura_Caja.txtNroCaja.setText(jTable1.getValueAt(fila, 1).toString());
            FrmApertura_Caja.txtMontoApertura.setText(jTable1.getValueAt(fila, 2).toString());
            FrmApertura_Caja.txtmontocierre.setText(jTable1.getValueAt(fila, 3).toString());
            FrmApertura_Caja.txtID.setText(jTable1.getValueAt(fila, 7).toString());
            FrmApertura_Caja.jFechaApertura.setDate(Date.valueOf(jTable1.getValueAt(fila, 4).toString()));
            FrmApertura_Caja.txtDocumento.setText(jTable1.getValueAt(fila, 9).toString());
            FrmApertura_Caja.txtnombreapellido.setText(jTable1.getValueAt(fila, 8).toString());
            FrmApertura_Caja.opciones = "editar";
//            FrmApertura_Caja.as.setText("EDITAR");
            this.dispose();
        }
    }

    DecimalFormat formato = new DecimalFormat("###,###.##");

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVista2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JLabel lbltitulovista;
    public static javax.swing.JLabel lbltotalregistros;
    public static javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
